### ISSUE TITLE
Error when loading a .jl script with nvim

### ISSUE THREAD

**Issue by jambo6** [JuliaEditorSupport/deoplete-julia#14]
Hi,

I've been trying to setup deoplete and julia on nvim, deoplete works fine, however when I install `deoplete-julia` and try to open a `.jl` file I receive the following error. 

Any ideas?

```
[deoplete] Traceback (most recent call last):
  File "/Users/jambo/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 604, in _on_event
    source.on_event(context)
  File "/Users/jambo/.config/nvim/plugged/deoplete-julia/rplugin/python3/deoplete/sources/julia.py", line 70, in on_event
    self.__make_cache()
  File "/Users/jambo/.config/nvim/plugged/deoplete-julia/rplugin/python3/deoplete/sources/julia.py", line 87, in __make_cache
    for filename in self.__get_tagfiles():
  File "/Users/jambo/.config/nvim/plugged/deoplete-julia/rplugin/python3/deoplete/sources/julia.py", line 99, in __get_tagfiles
    refered_tagfiles = get_refered_tagfiles(self.vim)
  File "/Users/jambo/.config/nvim/plugged/deoplete-julia/rplugin/python3/deoplete/sources/julia.py", line 43, in get_refered_tagfiles
    jltag_proc = subprocess.Popen([JULIA_PATH, str(JLTAG_PATH), "refer", current_filename],
  File "/Users/jambo/.config/nvim/env/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/jambo/.config/nvim/env/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'julia'
Exception during julia.on_event for event 'Init': [Errno 2] No such file or directory: 'julia'.  Use :messages / see above for error details.
```

**Comment by oxinabox** [comment]
This package is deprecated.
It doesn't work on anything newer than 0.5

I recommend LanguageServer.jl

**Comment by jambo6** [comment]
Ah right, thanks!
